### ISSUE TITLE
New update

### ISSUE THREAD

**Issue by Khebotz** [recitativonika/teneo-bot#16]
Error like this for new update. : /data/data/com.termux/files/home/teneo-bot/index.js:144
  console.log(chalk.whiteBright(`Email: ${accounts[index].email}`));
                                                          ^

TypeError: Cannot read properties of undefined (reading 'email')
    at displayAccountData (/data/data/com.termux/files/home/teneo-bot/index.js:144:59)
    at initialize (/data/data/com.termux/files/home/teneo-bot/index.js:103:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)

even use vps still same.

**Comment by recitativonika** [comment]
I made some change, try pull the repo again!

**Comment by Khebotz** [comment]
work! thankss
