### ISSUE TITLE
Doesn't start 

### ISSUE THREAD

**Issue by shaonturaj** [recitativonika/teneo-bot#2]
root@vmi2196522:~/teneo-bot# node index.js
(node:364342) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
/root/teneo-bot/index.js:1
import axios from 'axios';
^^^^^^
SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:1029:16)
    at Module._compile (internal/modules/cjs/loader.js:1078:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
    at Module.load (internal/modules/cjs/loader.js:979:32)
    at Function.Module._load (internal/modules/cjs/loader.js:819:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12)
    at internal/main/run_main_module.js:17:47
![Screenshot_20241102_112928_Termius](https://github.com/user-attachments/assets/e5a18531-3ad9-477a-8295-35eca906a8b5)

**Comment by recitativonika** [comment]
Thanks for report, I found what the issue. I will fix it asap!

**Comment by recitativonika** [comment]
Fixed, please pull the repo again!
